<?php
$page_title = "Event Details";
$filter_base_url = "/";

require_once "includes/db.php";
$db = init_sqlite_db("db/site.sqlite", "db/init.sql");

$event_id = $_GET['id'] ?? NULL;

$sql_select_clause = "SELECT * FROM events";
$sql_where_clause = "";

if ($event_id) {
  $sql_where_clause = " WHERE (id=:event_id)";
}

$sql_query = $sql_select_clause . $sql_where_clause;

if ($event_id) {
  $result = exec_sql_query($db, $sql_query, array(':event_id' => $event_id));
} else {
  $result = exec_sql_query($db, $sql_query);
}
$events = $result->fetchAll();
$event = $events[0] ?? NULL;

$sql_tags_query = "SELECT tags.name AS 'tags.name'
                   FROM tags
                   INNER JOIN event_tags ON (tags.id = event_tags.tag_id)
                   WHERE (event_tags.event_id = :event_id)";

if ($event_id) {
  $result_tags = exec_sql_query($db, $sql_tags_query, array(':event_id' => $event_id));
  $event_tags = $result_tags->fetchAll();
} else {
  $event_tags = array();
}

$image_url = "/public/uploads/events/" . $event["id"] . "." . $event['image_ext'];
?>

<!DOCTYPE html>
<html lang="en">

<?php include "includes/meta.php" ?>

<body>
  <?php include "includes/header.php" ?>

  <main class="event-details">

    <div class="hero-container">
      <img src="<?php echo htmlspecialchars($image_url); ?>" alt="<?php echo htmlspecialchars($event["image_title"]); ?>">
    </div>

    <div class="details-container">

      <div class="details-content">

        <h1><?php echo htmlspecialchars($event['title']); ?></h1>

        <div class="event-info-section">

          <div class="info-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
              <line x1="16" y1="2" x2="16" y2="6"></line>
              <line x1="8" y1="2" x2="8" y2="6"></line>
              <line x1="3" y1="10" x2="21" y2="10"></line>
            </svg>
            <div>
              <div class="info-label">Date & Time</div>
              <div class="info-value"><?php echo htmlspecialchars($event['time']); ?></div>
            </div>
          </div>

          <div class="info-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
              <circle cx="12" cy="10" r="3"></circle>
            </svg>
            <div>
              <div class="info-label">Location</div>
              <div class="info-value"><?php echo htmlspecialchars($event['location']); ?></div>
            </div>
          </div>

          <div class="info-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path>
              <circle cx="9" cy="7" r="4"></circle>
              <path d="M22 21v-2a4 4 0 0 0-3-3.87"></path>
              <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
            </svg>
            <div>
              <div class="info-label">Hosted by</div>
              <div class="info-value"><?php echo htmlspecialchars($event['host_organization']); ?></div>
            </div>
          </div>

        </div>

        <?php if (!empty($event_tags)) { ?>
          <div class="event-tags">
            <?php foreach ($event_tags as $tag) { ?>
              <span class="tag"><?php echo htmlspecialchars($tag['tags.name']); ?></span>
            <?php } ?>
          </div>
        <?php } ?>

        <div class="event-description">
          <h2>About this event</h2>
          <p><?php echo nl2br(htmlspecialchars($event['description'])); ?></p>
        </div>

        <div class="event-citations">
          <p>Content generated by ChatGPT</p>
          <?php if (!empty($event['image_citation'])) { ?>
            <p>Image: <?php echo htmlspecialchars($event['image_citation']); ?></p>
          <?php } ?>
        </div>

      </div>

    </div>

  </main>

  <script>
    function copyToClipboard() {
      navigator.clipboard.writeText(window.location.href).then(() => {
        alert('Link copied to clipboard!');
      }).catch(() => {
        alert('Share: ' + window.location.href);
      });
    }
  </script>
</body>

</html>
