<?php
$image_url = "/public/uploads/events/" . $event["id"] . "." . $event['image_ext'];
?>

<a href="/event?<?php echo http_build_query(array('id' => $event_id)); ?>" class="event-card">
  <img src="<?php echo htmlspecialchars($image_url); ?>" alt="<?php echo htmlspecialchars($event["image_file"]); ?>">

  <h3><?php echo $title; ?></h3>

  <p class="time"><?php echo $time; ?></p>

  <p class="location"><?php echo $location; ?></p>
  <p class="location">Citation: Content generated by ChatGPT</p>
  <?php if (!empty($event['image_citation'])) { ?>
    <p class="location">Image: <?php echo htmlspecialchars($event['image_citation']); ?></p>
  <?php } ?>

</a>
