<?php
$image_url = "/public/uploads/events/" . $event["id"] . "." . $event['image_ext'];
?>

<div class="event-tile">
    <img src="<?php echo htmlspecialchars($image_url); ?>" alt="<?php echo htmlspecialchars($event["image_file"]); ?>" class="thumbnail">


    <div class="event-info">
        <h3><?php echo $title; ?></h3>
        <p class="time"><?php echo $time; ?></p>
        <p class="location"><?php echo $location; ?></p>
        <p class="time">Citation: Content generated by ChatGPT</p>

        <?php if (!empty($event['image_citation'])) { ?>
            <p class="time">Image: <?php echo htmlspecialchars($event['image_citation']); ?></p>
        <?php } ?>

    </div>

    <div class="event-actions">
        <a href="/admin/edit?<?php echo http_build_query(array('id' => $event_id)); ?>" class="edit-button">Edit</a>
        <a href="?confirm_delete=<?php echo $event_id; ?>" class="delete-button">Delete</a>
    </div>
</div>
